markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Preston Pham
production_url : http://prestonp.github.com
description: "prestonnnn"
disqus_shortname: prestonpham
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Preston Alan Pham
  github : prestonp
  twitter : prestonp08
